### PR TITLE
Translate `library/concurrent.po` & `library/concurrency.po`

### LINKED ISSUE #151: Translate `library/concurrent.po` & `library/concurrency.po`

### PR DESCRIPTION
**Pull request by mattwang44**
`library/concurrent.po`:

image

`library/concurrency.po`:

image

### CODE REVIEW

**Review by josix — CHANGES_REQUESTED** [review]
Seems like there are two sentences(`../../library/concurrent.futures.rst:14` and `../../library/concurrent.futures.rst:17`) haven't been translated yet?

**Comment by mattwang44** [comment]
> Seems like there are two sentences(`../../library/concurrent.futures.rst:14` and `../../library/concurrent.futures.rst:17`) haven't been translated yet?

@josix  `concurrent.futures` is not covered in this PR (and there are more than two untranslated strings, which will be handled by another PR in the future). I translated one line in this file because it has identical source string with `../../library/concurrent.rst:6`. I believe it can be reviewed/merged together here.

**Comment by josix** [comment]
Got it! That's merge this PR.

**Review by josix — APPROVED** [review]
LGTM!

**Pull request merged**
