### PR TITLE
docs(makefile): add autodocumenting to makefile

### PR DESCRIPTION
**Pull request by josix**
Add autodocumenting to makefile, which works as following,

image

### CODE REVIEW

**Comment by mattwang44** [comment]
The GitHub Actions scripts use the `make` command (which is equivalent to `make all` before the change in this PR) for CI. This PR alters the behavior of `make` and thus modifying the `make` commands to `make all` in CI scripts are required.

**Review by mattwang44 — CHANGES_REQUESTED** [review]
The GitHub Actions scripts use the `make` command (which is equivalent to `make all` before the change in this PR) for CI. This PR alters the behavior of `make` and thus modifying the `make` commands to `make all` in CI scripts are required.

The CI simply prints the help msg and would be always passed:
https://github.com/python/python-docs-zh-tw/runs/5166355481?check_suite_focus=true

**Comment by josix** [comment]
> The GitHub Actions scripts use the `make` command (which is equivalent to `make all` before the change in this PR) for CI. This PR alters the behavior of `make` and thus modifying the `make` commands to `make all` in CI scripts are required.
> 
> The CI simply prints the help msg and would be always passed: https://github.com/python/python-docs-zh-tw/runs/5166355481?check_suite_focus=true

Thanks for reminding me. I've fixed that, please have a look.

**Review by mattwang44 — APPROVED** [review]
LGTM

One little thing that can possibly do is to move the python script from Makefile to a newly-created python script (e.g. `scripts/print_makefile_help_msg.py`) but we can start this once we think it's necessary.

**Pull request merged**
