### PR TITLE
Remove Fuzzy #500

### PR DESCRIPTION
**Pull request by ajaya0**

### CODE REVIEW

**Comment by mattwang44** [comment]
> Once the sentence has been corrected, you can remove the "fuzzy" mark line.

you did not correct the translation

**Comment by ajaya0** [comment]
can you explain more and what do and which sentence

**Comment by mattwang44** [comment]
@ajaya0 

The string right after `msgid` (L138) is the original English sentence in the Python official document, while the string after `msgstr` (L139) is its Traditional Chinese translation. The `#, fuzzy` tag (L137) indicates that the current translation of the entry is not accurate enough. You can only remove the fuzzy tag after you fix the Chinese translation at L139.

**Comment by ajaya0** [comment]
sir check my new pull request

**Comment by mattwang44** [comment]
I did not see your new PR

**Pull request closed without merging**
