### PR TITLE
Translate tutorial/classes

### PR DESCRIPTION
**Pull request by josix**
To resolve issue #4 
- [x] 9.1 ~ 9.3.3
    - [x] 9.3.4. Method Objects
    - [x] 9.3.5. Class and Instance Variables
- [x] 9.4. Random Remarks
- [x] 9.5. Inheritance
    - [x] 9.5.1 Multiple Inheritance
- [x] 9.6 Private Variables
- [ ] 9.7. Odds and Ends
- [ ] 9.8 Iterators
- [ ] 9.9. Generators
- [ ] 9.10. Generator Expressions

All suggestions are welcome.
Please correct me if any translation is not appropriate, thank you.

### CODE REVIEW

**Comment by josix** [comment]
I found that I have the typo on the above two commit messages which are 3.3.4 should be 9.3.4 and 3.3.5 should be 9.3.5.
Sorry about this misleading.

**Comment by StevenHsuYL** [comment]
Thanks for your effort, josix.
I would continue the translation work based on this PR later.

**Comment by josix** [comment]
Thank you @StevenHsuYL! Feel free to contact me if there is any question about my previous translations.

**Comment by josix** [comment]
Close this PR since it is duplicated with #77

**Pull request closed without merging**
