### PR TITLE
docs(howto/sockets.po): 翻譯 `IPC` 與 `Using a Socket` 區塊 (#493)

### PR DESCRIPTION
**Pull request by cschan1828**
* docs(howto/sockets.po): 翻譯 `IPC` 與 `Using a Socket` 區塊

gh-466

### CODE REVIEW

**Comment by cschan1828** [comment]
Cherry-pick this commit from 3.11 to 3.12. It has been reviewed already.

**Comment by cschan1828** [comment]
Original PR #493

**Comment by mattwang44** [comment]
sorry for my late response.
i can do the porting to 3.12 manually and the porting PR (like this one) is not required. Thanks anyway!

**Review by mattwang44 — APPROVED** [review]

**Comment by cschan1828** [comment]
Got it. No problem. I just think it is a minor issue which I can address by myself.

**Pull request merged**
