### PR TITLE
Translate `library/operator.po`

### LINKED ISSUE #170: Translate `library/operator.po`

### PR DESCRIPTION
**Pull request by mattwang44**
fix #170

preview:

image

### CODE REVIEW

**Comment by mattwang44** [comment]
@tomatoprinx, would you be interested in reviewing this PR?

**Comment by tomatoprinx** [comment]
No problems. I'll review this before next week 🎃

**Review by tai271828 — APPROVED** [review]
Skimmed the preview and it looks good to me \o/

**Comment by mattwang44** [comment]
@tai271828 thanks for helping out!
Please confirm the invitation for granting you the access as a reviewer. I'll merge this one afterwards.

**Review by tai271828 — APPROVED** [review]

**Pull request merged**
