### PR TITLE
Errors correct "//" 

### PR DESCRIPTION
**Pull request by AlexWUrobot**
Thank you

### CODE REVIEW

**Comment by adrianliaw** [comment]
Hi @AlexWUrobot, just in case if you got confused, you don't have to create a new branch and open a new PR just for fixing a previous PR! You can keep pushing onto your add-error branch which constructs #49, could you please re-apply it on `add-error` branch and push it there? That would make the discussion flow in a better way, thanks!

**Comment by adrianliaw** [comment]
@AlexWUrobot Thank you so much for doing that for me. I guess you'll have to verify that `git branch` prints out `add-error` on your local machine before you do `git push origin HEAD`, please let me know if it went wrong even you've verified it.

**Comment by adrianliaw** [comment]
@AlexWUrobot That definitely works as everything is explicit, but does it work if you 1. verify `git branch` prints out `add-error` 2. do `git push origin HEAD`?

**Comment by adrianliaw** [comment]
@AlexWUrobot 不好意思，我想再確認一次你說的意思。你的意思是說如果你執行 `git push origin HEAD` 的話就會正確推到 `add-error`，而不是這裡嗎？如果是的話，我就可以確認我在 README 裡面寫的指示沒有錯。

**Comment by mattwang44** [comment]
closed by #76.

**Pull request closed without merging**
